/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Buildings': '建筑',
    'Challenges': '挑战',
    'Click one of the buttons on the left to start a challenge!': '点击选择左侧一个挑战按钮来开启挑战!',
    'Current Challenge: None': '正在进行的挑战:无',
    'Current Challenges: No Accelerators [Transcension]': '正在进行的挑战:无加速（超越挑战）',
    'Export the game here.': '在这里导出游戏',
    'No Accelerator Challenge': '无加速挑战',
    'No background: Unachieved, nothing special.': '没有背景色:未完成，没有加成',
    'No Multiplier Challenge': '无加倍挑战',
    'No Shards Challenge': '无碎片挑战',
    'Prestige': '转生',
    'Prism Rune': '棱柱符文',
    'Purple background: Unachieved, provides bonus multiplier.': '紫色背景:未完成，提供加成',
    'Reincarnation': '转世',
    'Research': '研究',
    'Runes': '符文',
    'SACRIFICE': '献祭',
    'Settings': '选项',
    'Speed Rune': '加速符文',
    'Successfully imported your savefile. Go nuts!': '存档已保存，去疯吧!',
    'Tax+': '税收+',
    'Thanks to researches, your effective levels are increased by': '通过研究，你的提高了',
    'Thrift Rune': '节俭符文',
    'To leave a challenge, press the hotkey listed above OR click on the red Challenge "C" button on the reset buttons on top.': '想要退出挑战，你可以按列表里的快捷键或者点击上方转生按钮右边的C按钮',
    'To leave a reincarnation challenge, press the grey Challenge "C" instead!': '如果想要退出转世挑战，请按灰色的C',
    'Toggle amount to buy': '批量购买',
    'Toggle amount to use per sacrifice': '批量献祭',
    'Transcension': '超越',
    'Upgrades': '升级',
    'Hover over an achievement to view information.': '鼠标悬停在成就上查看详细信息',
    'Achievements': '成就',
    'Copied to clickboard! Paste it somewhere safe.': '存档已导出至剪贴板!请把它粘贴在安全的地方',
    'Import the game here.': '在这里导入游戏',
    'Confirmation Toggles': '转生时的弹窗询问',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Augments': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    'Prestige when exponent of diamonds increases by': '自动转生当转生后钻石位数增加',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Coins, Coin Producers, Coin Upgrades, and Crystals are reset, but in return you gain diamonds and a few offerings.': '金币,金币生产者,金币升级,水晶都会被重置,但你可以获得钻石和少量祭品',
    'A Loyal Employee: Hire your first worker.': '一个忠实的员工:招募第一个工人',
    'Small Business: Hire 10 workers.': '小生意:招募10个工人',
    'Now we\'re synergizing!: Hire 100 workers.': '现在我们在协作了!:招募100个工人',
    'Gaining Redundancies: Hire 1,000 workers.': '该裁员了:招募1000个工人',
    'A cog in the machine: Hire 5,000 workers.': '机器上的齿轮:招募5000个工人',
    'A nail in the machine: Hire 10,000 workers.': '机器上的钉子:招募10,000个工人',
    'Are we even in the machine anymore?: Hire 20,000 workers.': '我们还在机器里吗？:招募20,000个工人',
    'STONKS!!!: Purchase 1 Investment.': '进击!!!:购买一个投资',
    'Planning ahead: Purchase 10 Investments.': '提前计划:购买10个投资',
    'Inside Trading: Purchase 100 Investments.': '内部交易:购买100个投资',
    'Outside Trading?: Purchase 1,000 Investments.': '外部交易?:购买1000个投资',
    'Market Tackover: Purchase 5,000 Investments.': '接管市场:购买5000个投资',
    'Trickle-Down Economics: Purchase 10,000 Investments.': '滴入式经济学:购买10,000个投资',
    'Eliminated Regulation: Purchase 20,000 Investments.': '拒绝调控:购买20,000个投资',
    'Stationery!: Build 1 Printer.': '文具!:购买一台打印机',
    'Printing Press: Build 10 Printers.': '印刷机:购买10台打印机',
    'It prints free money!: Build 100 Printers.': '它印的是免费的钱!:购买100台打印机',
    'Solving Our Debts: Build 1,000 Printers.': '解决我们的债务:购买1000台打印机',
    'Monopolizing the market: Build 5,000 Printers.': '垄断市场:购买5000台打印机',
    'We\'re running out of Ink!: Build 10,000 Printers.': '我们的墨水不够用了!:购买10,000台打印机',
    '3D-printing the universe: Build 20,000 Printers.': '3D打印宇宙:购买20,000台打印机',
    '': '',
    'Increase production of Workers per producer bought.': '基于已购买的生产者提供工人的加成',
    'Increase production of Investments per producer bought.': '基于已购买的生产者提供投资的加成',
    'Increase production of Printers per producer bought.': '基于已购买的生产者提供打印机的加成',
    'Increase production of Mints per producer bought.': '基于已购买的生产者提供铸币厂的加成',
    'Increase production of Alchemies per producer bought.': '基于已购买的生产者提供炼金术的加成',
    'Increase all production by 25% per producer bought.': '每个购买的生产者会增加所有产量25%',
    'Gain free multipliers based on your purchased Alchemies.': '根据炼金术等级获得免费的加倍',
    'Effect: Worker Production': '效果:工人产量',
    'Effect: Investment Production': '效果:投资产量',
    'Effect: Printer Production': '效果:打印机产量',
    'Effect: Mint Production': '效果:铸币厂产量',
    'Effect: Alchemy Production': '效果:炼金术产量',
    'Effect: All Coin production': '效果:所有金币产量',
    'Effect: Gain': '效果:获得',
    'Gain 1 free Accelerator per 7 purchased Multipliers.': '每购买7个加倍可以获得一个免费的加速器',
    'Gain 1 free Multiplier per 10 purchased Accelerators.': '每购买10个加速器可以获得一个免费的加倍',
    'Improve Workers based on the first 750 purchased Investments.': '基于前750个已购买投资提供工人的加成',
    'Accelerators improve generation production by 2% each.': '加速器每个提供繁衍效果2%',
    'Effect: Generator efficiency': '效果:繁衍效果',
    'Each prestige multiplies production by 1.01 (Max: 1e4x).': '每次转生使倍率增强1.01(最大:1e4倍)',
    'Effect: All Coin production': '效果:所有金币产出',
    'Augments buff the production of Investments.': '强化(超越标签)会增强投资',
    'Free Accelerators buff generation of Printers.': '免费的加速器会增强打印机的繁衍效果',
    'Effect: Printer Generation': '效果:打印机繁衍效果',
    'Free Accelerators buff generation of Mints.': '免费的加速器会增强铸币厂的繁衍效果',
    'Effect: Mint Generation': '效果:铸币厂繁衍效果',
    'Acceleration Multiplier buffs Diamond gain.': '加速器和加倍的加成会额外影响钻石获取',
    'Multiply Mint production by 1e+100.': '铸币厂获得1e100的加成',
    'Multiply Printer production based on Mythos Shards.': '基于神话碎片提高打印机加成',
    'Multiply Investment production based on Mythos.': '基于神话提高投资加成',
    'Coin upgrade 1 is raised to the eleventh power.': '金币升级每级提供11倍的效果',
    'Effect: All coin production is further multiplied by': '效果:大幅提升所有金币产量',
    'Gain 1 Multiplier and 5 Accelerators plus 1% more free Multipliers/Accelerators.': '获得1个加倍和5个加速器以及1%的免费加速器/加倍',
    'Gain 1 Multiplier and 4 Accelerators plus 1% more free Multipliers/Accelerators.': '获得1个加倍和4个加速器以及1%的免费加速器/加倍',
    'Gain 1 Multiplier and 3 Accelerators plus 1% more free Multipliers/Accelerators.': '获得1个加倍和3个加速器以及1%的免费加速器/加倍',
    'Gain 1 Multiplier and 2 Accelerators plus 1% more free Multipliers/Accelerators.': '获得1个加倍和2个加速器以及1%的免费加速器/加倍',
    'Gain 1 Multiplier and 1 Accelerators plus 1% more free Multipliers/Accelerators.': '获得1个加倍和1个加速器以及1%的免费加速器/加倍',
    'Gain a free Accelerator Boost plus 2.5% more free Accelerator Boosts.': '获得1个加速器加成以及2.5%加速器加成',
    'Gain free Accelerators based on unspent Coins.': '基于未使用的金币获得免费加速器',
    'Gain a free Multiplier per 160 Coin producers bought.': '每购买160个金币生产者获得额外一个加倍',
    'Gain a free Accelerator per 80 Coin producers bought.': '每购买80个金币生产者获得额外一个加速器',
    'Gain free Multipliers based on unspent Coins.': '基于未使用的金币获得免费加倍',
    'Gain 1 free Accelerator Boost per 2,000 Coin producers bought.': '每购买2000个金币生产者获得额外一个加速器加成',
    'Gain free Accelerators based on Unspent Diamonds.': '基于未使用的钻石获得免费加速器',
    'Gain 1 free Multiplier for each Accelerator Boost owned.': '每个拥有的加速器加成额外提供一个加倍',
    'Gain 3% more free Accelerators and Multipliers.': '获得3%的免费加速器和加倍',
    'Gain 2% more free Accelerators and Multipliers [up to 5%].': '获得2%的免费加速器和加倍[最高5%]',
    'Gain 1% more free Accelerators and Multipliers [up to 5%].': '获得1%的免费加速器和加倍[最高5%]',
    'Gain 3% more free Accelerators and Multipliers [up to 5%].': '获得3%的免费加速器和加倍[最高5%]',
    'Gain 4% more free Accelerators and Multipliers [up to 5%].': '获得4%的免费加速器和加倍[最高5%]',
    'Gain 5% more free Accelerators and Multipliers [up to 5%].': '获得5%的免费加速器和加倍[最高5%]',
    'Multiply production based on unspent Mythos.': '基于未使用的神话提供加成',
    'Effect: Welcome to Transcension! Coin production is multiplied by': '效果:欢迎来到超越!提高金币产出',
    'Multiply Mythos Shard production based on unspent Diamonds.': '基于未使用的钻石提高神话碎片加成',
    'Effect: All mythos shard producers are going into overdrive:': '效果:所有神话碎片生产者都超载了:',
    'Multiply coin production by 1.01 per transcension (Max: 1e30x).': '每次超越提供1.01金币加成(最高:1e30倍)',
    'Effect: Multiply all coin production by': '效果:所有金币产量提高',
    'Multiply Mythos gain on Transcend by 1.01 per transcension (Max: 1e6x).': '每次超越使超越获得1.01额外神话加成(最高:1e6倍)',
    'Effect: Multiply Mythos gained in Transcension by': '效果:超越获得的神话加成',
    'Gain free Accelerators based on Mythos Shards.': '基于神话碎片获得免费的加速器',
    'Accelerator Boosts are 5% stronger and do not reset prestige features.': '加速器加成效果提高5%,并且不会重置转生加成',
    'Effect: It\'s kinda self-evident, ain\'t it?': '效果:这真是个亲切的升级,不是吗',
    'Multiply Mythos Shard production based on your AP.': '基于你的成就点加成神话碎片产量',
    'Effect: Mythos-tier producers production': '效果:神话碎片生产者产量提高',
    'Multiply production based on owned Accelerators and Multipliers.': '基于已有的加速器和加倍提供产量加成',
    'Effect: Multiply coin production by a factor of': '效果:大幅提升金币产量',
    'Gain free Multipliers based on unspent Mythos.': '基于未使用的神话获得免费的加倍',
    'Gain +25% free Accelerators and Multipliers, but ONLY while doing challenges.': '获得25%免费的加速器和加倍,但只能在挑战中生效',
    'Effect: It\'s quite obvious what the benefit is, but you must be in a challenge for it to be in use!': '一个相当巨大的加成,但你必须在挑战中才能使用它',
    'Alchemies will produce Coin Mints.': '炼金术会繁衍铸币厂',
    'Effect: All you need to know is right above this message!': '效果:你想要知道的东西都在这条信息上面!',
    'Coin Mints will produce Printers.': '铸币厂会繁衍打印机',
    'Printers will produce Investments.': '打印机会繁衍投资',
    'Investments will produce Workers.': '投资会繁衍工人',
    'Purchased Workers will produce Alchemies.': '购买的工人会繁衍炼金术',
    'Refineries can produce Alchemies equal to Refineries owned raised to 0.10': '炼油厂将按已有的0.10生产炼金术',
    'Refinery -> Alchemy exponent increased from 0.10 to 0.25.': '炼油厂生产炼金术的效率从0.10提高至0.25',
    'Refinery -> Alchemy exponent increased from 0.25 to 0.50': '炼油厂生产炼金术的效率从0.25提高至0.50',
    'Refinery -> Alchemy exponent increased from 0.50 to 0.75': '炼油厂生产炼金术的效率从0.50提高至0.75',
    'Refinery -> Alchemy exponent increased from 0.75 to 1': '炼油厂生产炼金术的效率从0.75提高至1',
    'Augments can produce Pandora Boxes equal to Augments owned raised to 0.08': '强化将按已有的0.08生产潘多拉盒子',
    'Augment -> Box exponent increased from 0.08 to 0.16': '强化生产潘多拉盒子的效率从0.08提高至0.16',
    'Augment -> Box exponent increased from 0.16 to 0.24': '强化生产潘多拉盒子的效率从0.16提高至0.24',
    'Augment -> Box exponent increased from 0.24 to 0.32': '强化生产潘多拉盒子的效率从0.24提高至0.32',
    'Augment -> Box exponent increased from 0.32 to 0.40': '强化生产潘多拉盒子的效率从0.32提高至0.40',
    'Protons can produce Grandmasters equal to Protons owned raised to 0.05': '质子将按已有的0.05生产大师',
    'Protons -> Grandmaster exponent increased from 0.05 to 0.10': '质子生产大师的效率从0.05提高至0.10',
    'Protons -> Grandmaster exponent increased from 0.10 to 0.15': '质子生产大师的效率从0.10提高至0.15',
    'Protons -> Grandmaster exponent increased from 0.15 to 0.20': '质子生产大师的效率从0.15提高至0.20',
    'Protons -> Grandmaster exponent increased from 0.20 to 0.25': '质子生产大师的效率从0.20提高至0.25',
    'Automatically buy Workers if affordable.': '自动购买工人',
    'Automatically buy Investments if affordable.': '自动购买投资',
    'Automatically buy Printers if affordable.': '自动购买打印机',
    'Automatically buy Coin Mints if affordable.': '自动购买铸币厂',
    'Automatically buy Alchemies if affordable.': '自动购买炼金术',
    'Automatically buy Accelerators if affordable.': '自动购买加速器',
    'Automatically buy Multipliers if affordable.': '自动购买加倍',
    'Automatically buy Accelerator Boosts if affordable.': '自动购买加速器加强',
    'Unlock Automatic Transcensions.': '解锁自动超越',
    'Automatically buy Generators if affordable.': '自动购买繁衍升级',
    'Automatically buy Coin Upgrades.': '自动购买金币升级',
    'Automatically buy Prestige Upgrades.': '自动购买钻石升级',
    'Generate 1% of Diamond Gain from prestiging per second.': '每秒产出1%转生可获得的钻石',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Effect: Gain': '效果:获得',
    'Pandora\'s Boxes': '潘多拉的盒子',
    'Pickaxes': '十字镐',
    'Coal Rigs': '煤矿钻机',
    'Coal Plants': '煤电厂',
    'Refineries': '炼油厂',
    'Cost:': '消耗:',
    'Effect: ': '效果:',
    'Workers': '工人',
    'Accelerator Boost': '加速器加成',
    'Investments': '投资',
    'Printers': '打印机',
    'Coin Mints': '铸币厂',
    'Alchemies': '炼金术',
    'Coin/Sec': '金币/秒',
    'Accelerators': '加速器',
    'Multipliers': '加倍',
    'Augments': '强化',
    'Enchantments': '附魔',
    'Wizards': '法师',
    'Oracles': '神谕',
    'Grandmasters': '大师',
    '': '',
    '': '',
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    'BOUGHT!': '已购买!',
    'COMPLETED!': '已完成!',
    'Multipliers through magic!': '加倍',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'the production!': '产量加成!',
    'Accelerator Boosts': '加速器加成',
    'Accelerator Boosts.': '加速器加成',
    'Accelerators.': '加速器',
    '[Stacks with upgrade 1]!': '[从第一级开始计算]!',
    'more Diamonds on prestige': '额外钻石在转生时',
    '[Enter a number above to toggle]': '[在上方输入一个数字来控制]',
    'free Multipliers.': '免费的加倍',
    'free multipliers from bought Alchemies.': '免费的加倍基于已购买的炼金术',
    'free Accelerators.': '免费的加速器',
    'Coins': '金币',
    'Diamonds': '钻石',
    'Mythos': '神话',
    'Multipliers': '加倍',
    'Multipliers.': '加倍',
    'Accelerators!': '加速器!',
    '': '',
    '': '',
    '': '',
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);