Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Coin.png" -OutFile "Pictures/Coin.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Offering.png" -OutFile "Pictures/Offering.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Diamond.png" -OutFile "Pictures/Diamond.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Crystal.png" -OutFile "Pictures/Crystal.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Obtainium.png" -OutFile "Pictures/Obtainium.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Mythos.png" -OutFile "Pictures/Mythos.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/MythosShard.png" -OutFile "Pictures/MythosShard.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Particle.png" -OutFile "Pictures/Particle.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Atom.png" -OutFile "Pictures/Atom.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Quark.png" -OutFile "Pictures/Quark.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Prestige.png" -OutFile "Pictures/Transparent Pics/Prestige.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Transcend.png" -OutFile "Pictures/Transparent Pics/Transcend.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Reincarnate.png" -OutFile "Pictures/Transparent Pics/Reincarnate.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AcceleratorBoost.png" -OutFile "Pictures/Transparent Pics/AcceleratorBoost.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Challenge.png" -OutFile "Pictures/Transparent Pics/Challenge.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/ChallengeReincarnation.png" -OutFile "Pictures/Transparent Pics/ChallengeReincarnation.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/CoinOne.png" -OutFile "Pictures/Transparent Pics/CoinOne.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/CoinTen.png" -OutFile "Pictures/Transparent Pics/CoinTen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/CoinHundred.png" -OutFile "Pictures/Transparent Pics/CoinHundred.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Tier1.png" -OutFile "Pictures/Tier1.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Tier2.png" -OutFile "Pictures/Tier2.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Tier3.png" -OutFile "Pictures/Tier3.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Tier4.png" -OutFile "Pictures/Tier4.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Tier5.png" -OutFile "Pictures/Tier5.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Accelerator.png" -OutFile "Pictures/Accelerator.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Multiplier.png" -OutFile "Pictures/Multiplier.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/AcceleratorBoost.png" -OutFile "Pictures/AcceleratorBoost.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Coin.png" -OutFile "Pictures/Coin.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Diamond.png" -OutFile "Pictures/Diamond.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Mythos.png" -OutFile "Pictures/Mythos.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Particle.png" -OutFile "Pictures/Particle.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Automation.png" -OutFile "Pictures/Automation.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Generators.png" -OutFile "Pictures/Generators.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin1.png" -OutFile "Pictures/Transparent Pics/Coin1.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin2.png" -OutFile "Pictures/Transparent Pics/Coin2.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin3.png" -OutFile "Pictures/Transparent Pics/Coin3.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin4.png" -OutFile "Pictures/Transparent Pics/Coin4.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin5.png" -OutFile "Pictures/Transparent Pics/Coin5.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin6.png" -OutFile "Pictures/Transparent Pics/Coin6.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin7.png" -OutFile "Pictures/Transparent Pics/Coin7.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin8.png" -OutFile "Pictures/Transparent Pics/Coin8.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin9.png" -OutFile "Pictures/Transparent Pics/Coin9.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin10.png" -OutFile "Pictures/Transparent Pics/Coin10.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin11.png" -OutFile "Pictures/Transparent Pics/Coin11.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin12.png" -OutFile "Pictures/Transparent Pics/Coin12.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin13.png" -OutFile "Pictures/Transparent Pics/Coin13.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin14.png" -OutFile "Pictures/Transparent Pics/Coin14.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin15.png" -OutFile "Pictures/Transparent Pics/Coin15.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin16.png" -OutFile "Pictures/Transparent Pics/Coin16.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin17.png" -OutFile "Pictures/Transparent Pics/Coin17.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin18.png" -OutFile "Pictures/Transparent Pics/Coin18.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin19.png" -OutFile "Pictures/Transparent Pics/Coin19.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Coin20.png" -OutFile "Pictures/Transparent Pics/Coin20.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond1.png" -OutFile "Pictures/Transparent Pics/Diamond1.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond2.png" -OutFile "Pictures/Transparent Pics/Diamond2.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond3.png" -OutFile "Pictures/Transparent Pics/Diamond3.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond4.png" -OutFile "Pictures/Transparent Pics/Diamond4.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond5.png" -OutFile "Pictures/Transparent Pics/Diamond5.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond6.png" -OutFile "Pictures/Transparent Pics/Diamond6.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond7.png" -OutFile "Pictures/Transparent Pics/Diamond7.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond8.png" -OutFile "Pictures/Transparent Pics/Diamond8.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond9.png" -OutFile "Pictures/Transparent Pics/Diamond9.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond10.png" -OutFile "Pictures/Transparent Pics/Diamond10.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond11.png" -OutFile "Pictures/Transparent Pics/Diamond11.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond12.png" -OutFile "Pictures/Transparent Pics/Diamond12.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond13.png" -OutFile "Pictures/Transparent Pics/Diamond13.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond14.png" -OutFile "Pictures/Transparent Pics/Diamond14.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond15.png" -OutFile "Pictures/Transparent Pics/Diamond15.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond16.png" -OutFile "Pictures/Transparent Pics/Diamond16.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond17.png" -OutFile "Pictures/Transparent Pics/Diamond17.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond18.png" -OutFile "Pictures/Transparent Pics/Diamond18.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond19.png" -OutFile "Pictures/Transparent Pics/Diamond19.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Diamond20.png" -OutFile "Pictures/Transparent Pics/Diamond20.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos1.png" -OutFile "Pictures/Transparent Pics/Mythos1.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos2.png" -OutFile "Pictures/Transparent Pics/Mythos2.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos3.png" -OutFile "Pictures/Transparent Pics/Mythos3.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos4.png" -OutFile "Pictures/Transparent Pics/Mythos4.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos5.png" -OutFile "Pictures/Transparent Pics/Mythos5.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos6.png" -OutFile "Pictures/Transparent Pics/Mythos6.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos7.png" -OutFile "Pictures/Transparent Pics/Mythos7.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos8.png" -OutFile "Pictures/Transparent Pics/Mythos8.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos9.png" -OutFile "Pictures/Transparent Pics/Mythos9.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos10.png" -OutFile "Pictures/Transparent Pics/Mythos10.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos11.png" -OutFile "Pictures/Transparent Pics/Mythos11.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos12.png" -OutFile "Pictures/Transparent Pics/Mythos12.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos13.png" -OutFile "Pictures/Transparent Pics/Mythos13.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos14.png" -OutFile "Pictures/Transparent Pics/Mythos14.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos15.png" -OutFile "Pictures/Transparent Pics/Mythos15.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos16.png" -OutFile "Pictures/Transparent Pics/Mythos16.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos17.png" -OutFile "Pictures/Transparent Pics/Mythos17.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos18.png" -OutFile "Pictures/Transparent Pics/Mythos18.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos19.png" -OutFile "Pictures/Transparent Pics/Mythos19.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Mythos20.png" -OutFile "Pictures/Transparent Pics/Mythos20.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle1.png" -OutFile "Pictures/Transparent Pics/Particle1.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle2.png" -OutFile "Pictures/Transparent Pics/Particle2.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle3.png" -OutFile "Pictures/Transparent Pics/Particle3.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle4.png" -OutFile "Pictures/Transparent Pics/Particle4.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle5.png" -OutFile "Pictures/Transparent Pics/Particle5.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle6.png" -OutFile "Pictures/Transparent Pics/Particle6.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle7.png" -OutFile "Pictures/Transparent Pics/Particle7.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle8.png" -OutFile "Pictures/Transparent Pics/Particle8.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle9.png" -OutFile "Pictures/Transparent Pics/Particle9.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle10.png" -OutFile "Pictures/Transparent Pics/Particle10.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle11.png" -OutFile "Pictures/Transparent Pics/Particle11.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle12.png" -OutFile "Pictures/Transparent Pics/Particle12.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle13.png" -OutFile "Pictures/Transparent Pics/Particle13.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle14.png" -OutFile "Pictures/Transparent Pics/Particle14.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Particle15.png" -OutFile "Pictures/Transparent Pics/Particle15.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Reincarnate.png" -OutFile "Pictures/Transparent Pics/Reincarnate.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Reincarnate.png" -OutFile "Pictures/Transparent Pics/Reincarnate.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Reincarnate.png" -OutFile "Pictures/Transparent Pics/Reincarnate.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Reincarnate.png" -OutFile "Pictures/Transparent Pics/Reincarnate.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Reincarnate.png" -OutFile "Pictures/Transparent Pics/Reincarnate.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationOne.png" -OutFile "Pictures/Transparent Pics/AutomationOne.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationTwo.png" -OutFile "Pictures/Transparent Pics/AutomationTwo.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationThree.png" -OutFile "Pictures/Transparent Pics/AutomationThree.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationFour.png" -OutFile "Pictures/Transparent Pics/AutomationFour.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationFive.png" -OutFile "Pictures/Transparent Pics/AutomationFive.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationSix.png" -OutFile "Pictures/Transparent Pics/AutomationSix.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationSeven.png" -OutFile "Pictures/Transparent Pics/AutomationSeven.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationEight.png" -OutFile "Pictures/Transparent Pics/AutomationEight.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationNine.png" -OutFile "Pictures/Transparent Pics/AutomationNine.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationTen.png" -OutFile "Pictures/Transparent Pics/AutomationTen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationEleven.png" -OutFile "Pictures/Transparent Pics/AutomationEleven.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationTwelve.png" -OutFile "Pictures/Transparent Pics/AutomationTwelve.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationThirteen.png" -OutFile "Pictures/Transparent Pics/AutomationThirteen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationFourteen.png" -OutFile "Pictures/Transparent Pics/AutomationFourteen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationFifteen.png" -OutFile "Pictures/Transparent Pics/AutomationFifteen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationSixteen.png" -OutFile "Pictures/Transparent Pics/AutomationSixteen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationSeventeen.png" -OutFile "Pictures/Transparent Pics/AutomationSeventeen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationEighteen.png" -OutFile "Pictures/Transparent Pics/AutomationEighteen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationNineteen.png" -OutFile "Pictures/Transparent Pics/AutomationNineteen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/AutomationTwenty.png" -OutFile "Pictures/Transparent Pics/AutomationTwenty.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorOne.png" -OutFile "Pictures/Transparent Pics/GeneratorOne.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorTwo.png" -OutFile "Pictures/Transparent Pics/GeneratorTwo.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorThree.png" -OutFile "Pictures/Transparent Pics/GeneratorThree.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorFour.png" -OutFile "Pictures/Transparent Pics/GeneratorFour.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorFive.png" -OutFile "Pictures/Transparent Pics/GeneratorFive.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorSix.png" -OutFile "Pictures/Transparent Pics/GeneratorSix.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorSeven.png" -OutFile "Pictures/Transparent Pics/GeneratorSeven.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorEight.png" -OutFile "Pictures/Transparent Pics/GeneratorEight.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorNine.png" -OutFile "Pictures/Transparent Pics/GeneratorNine.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorTen.png" -OutFile "Pictures/Transparent Pics/GeneratorTen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorEleven.png" -OutFile "Pictures/Transparent Pics/GeneratorEleven.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorTwelve.png" -OutFile "Pictures/Transparent Pics/GeneratorTwelve.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorThirteen.png" -OutFile "Pictures/Transparent Pics/GeneratorThirteen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorFourteen.png" -OutFile "Pictures/Transparent Pics/GeneratorFourteen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorFifteen.png" -OutFile "Pictures/Transparent Pics/GeneratorFifteen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorSixteen.png" -OutFile "Pictures/Transparent Pics/GeneratorSixteen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorSeventeen.png" -OutFile "Pictures/Transparent Pics/GeneratorSeventeen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorEighteen.png" -OutFile "Pictures/Transparent Pics/GeneratorEighteen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorNineteen.png" -OutFile "Pictures/Transparent Pics/GeneratorNineteen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/GeneratorTwenty.png" -OutFile "Pictures/Transparent Pics/GeneratorTwenty.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement1.png" -OutFile "Pictures/Transparent Pics/Achievement1.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement2.png" -OutFile "Pictures/Transparent Pics/Achievement2.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement3.png" -OutFile "Pictures/Transparent Pics/Achievement3.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement4.png" -OutFile "Pictures/Transparent Pics/Achievement4.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement5.png" -OutFile "Pictures/Transparent Pics/Achievement5.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement6.png" -OutFile "Pictures/Transparent Pics/Achievement6.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement7.png" -OutFile "Pictures/Transparent Pics/Achievement7.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement8.png" -OutFile "Pictures/Transparent Pics/Achievement8.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement9.png" -OutFile "Pictures/Transparent Pics/Achievement9.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement10.png" -OutFile "Pictures/Transparent Pics/Achievement10.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement11.png" -OutFile "Pictures/Transparent Pics/Achievement11.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement12.png" -OutFile "Pictures/Transparent Pics/Achievement12.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement13.png" -OutFile "Pictures/Transparent Pics/Achievement13.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement14.png" -OutFile "Pictures/Transparent Pics/Achievement14.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement21.png" -OutFile "Pictures/Transparent Pics/Achievement21.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement15.png" -OutFile "Pictures/Transparent Pics/Achievement15.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement16.png" -OutFile "Pictures/Transparent Pics/Achievement16.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement17.png" -OutFile "Pictures/Transparent Pics/Achievement17.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement18.png" -OutFile "Pictures/Transparent Pics/Achievement18.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement19.png" -OutFile "Pictures/Transparent Pics/Achievement19.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement20.png" -OutFile "Pictures/Transparent Pics/Achievement20.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement22.png" -OutFile "Pictures/Transparent Pics/Achievement22.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement23.png" -OutFile "Pictures/Transparent Pics/Achievement23.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement24.png" -OutFile "Pictures/Transparent Pics/Achievement24.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement25.png" -OutFile "Pictures/Transparent Pics/Achievement25.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement26.png" -OutFile "Pictures/Transparent Pics/Achievement26.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement27.png" -OutFile "Pictures/Transparent Pics/Achievement27.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement28.png" -OutFile "Pictures/Transparent Pics/Achievement28.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement29.png" -OutFile "Pictures/Transparent Pics/Achievement29.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement30.png" -OutFile "Pictures/Transparent Pics/Achievement30.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement31.png" -OutFile "Pictures/Transparent Pics/Achievement31.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement32.png" -OutFile "Pictures/Transparent Pics/Achievement32.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement33.png" -OutFile "Pictures/Transparent Pics/Achievement33.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement34.png" -OutFile "Pictures/Transparent Pics/Achievement34.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement35.png" -OutFile "Pictures/Transparent Pics/Achievement35.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement36.png" -OutFile "Pictures/Transparent Pics/Achievement36.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement37.png" -OutFile "Pictures/Transparent Pics/Achievement37.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement38.png" -OutFile "Pictures/Transparent Pics/Achievement38.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement39.png" -OutFile "Pictures/Transparent Pics/Achievement39.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement40.png" -OutFile "Pictures/Transparent Pics/Achievement40.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement41.png" -OutFile "Pictures/Transparent Pics/Achievement41.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement42.png" -OutFile "Pictures/Transparent Pics/Achievement42.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement43.png" -OutFile "Pictures/Transparent Pics/Achievement43.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement44.png" -OutFile "Pictures/Transparent Pics/Achievement44.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement45.png" -OutFile "Pictures/Transparent Pics/Achievement45.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement46.png" -OutFile "Pictures/Transparent Pics/Achievement46.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement47.png" -OutFile "Pictures/Transparent Pics/Achievement47.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement48.png" -OutFile "Pictures/Transparent Pics/Achievement48.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement49.png" -OutFile "Pictures/Transparent Pics/Achievement49.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement50.png" -OutFile "Pictures/Transparent Pics/Achievement50.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement51.png" -OutFile "Pictures/Transparent Pics/Achievement51.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement52.png" -OutFile "Pictures/Transparent Pics/Achievement52.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement53.png" -OutFile "Pictures/Transparent Pics/Achievement53.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement54.png" -OutFile "Pictures/Transparent Pics/Achievement54.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement55.png" -OutFile "Pictures/Transparent Pics/Achievement55.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement56.png" -OutFile "Pictures/Transparent Pics/Achievement56.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement57.png" -OutFile "Pictures/Transparent Pics/Achievement57.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement58.png" -OutFile "Pictures/Transparent Pics/Achievement58.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement59.png" -OutFile "Pictures/Transparent Pics/Achievement59.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement60.png" -OutFile "Pictures/Transparent Pics/Achievement60.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement61.png" -OutFile "Pictures/Transparent Pics/Achievement61.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement62.png" -OutFile "Pictures/Transparent Pics/Achievement62.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement63.png" -OutFile "Pictures/Transparent Pics/Achievement63.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement64.png" -OutFile "Pictures/Transparent Pics/Achievement64.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement65.png" -OutFile "Pictures/Transparent Pics/Achievement65.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement66.png" -OutFile "Pictures/Transparent Pics/Achievement66.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement67.png" -OutFile "Pictures/Transparent Pics/Achievement67.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement68.png" -OutFile "Pictures/Transparent Pics/Achievement68.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement69.png" -OutFile "Pictures/Transparent Pics/Achievement69.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement70.png" -OutFile "Pictures/Transparent Pics/Achievement70.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement71.png" -OutFile "Pictures/Transparent Pics/Achievement71.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement72.png" -OutFile "Pictures/Transparent Pics/Achievement72.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement73.png" -OutFile "Pictures/Transparent Pics/Achievement73.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement74.png" -OutFile "Pictures/Transparent Pics/Achievement74.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement75.png" -OutFile "Pictures/Transparent Pics/Achievement75.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement76.png" -OutFile "Pictures/Transparent Pics/Achievement76.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement77.png" -OutFile "Pictures/Transparent Pics/Achievement77.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement78.png" -OutFile "Pictures/Transparent Pics/Achievement78.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement79.png" -OutFile "Pictures/Transparent Pics/Achievement79.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement80.png" -OutFile "Pictures/Transparent Pics/Achievement80.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement81.png" -OutFile "Pictures/Transparent Pics/Achievement81.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement82.png" -OutFile "Pictures/Transparent Pics/Achievement82.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement83.png" -OutFile "Pictures/Transparent Pics/Achievement83.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement84.png" -OutFile "Pictures/Transparent Pics/Achievement84.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement85.png" -OutFile "Pictures/Transparent Pics/Achievement85.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement86.png" -OutFile "Pictures/Transparent Pics/Achievement86.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement87.png" -OutFile "Pictures/Transparent Pics/Achievement87.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement88.png" -OutFile "Pictures/Transparent Pics/Achievement88.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement89.png" -OutFile "Pictures/Transparent Pics/Achievement89.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement90.png" -OutFile "Pictures/Transparent Pics/Achievement90.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement91.png" -OutFile "Pictures/Transparent Pics/Achievement91.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement92.png" -OutFile "Pictures/Transparent Pics/Achievement92.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement93.png" -OutFile "Pictures/Transparent Pics/Achievement93.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement94.png" -OutFile "Pictures/Transparent Pics/Achievement94.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement95.png" -OutFile "Pictures/Transparent Pics/Achievement95.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement96.png" -OutFile "Pictures/Transparent Pics/Achievement96.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement97.png" -OutFile "Pictures/Transparent Pics/Achievement97.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement98.png" -OutFile "Pictures/Transparent Pics/Achievement98.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement99.png" -OutFile "Pictures/Transparent Pics/Achievement99.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement100.png" -OutFile "Pictures/Transparent Pics/Achievement100.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement101.png" -OutFile "Pictures/Transparent Pics/Achievement101.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement102.png" -OutFile "Pictures/Transparent Pics/Achievement102.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement103.png" -OutFile "Pictures/Transparent Pics/Achievement103.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement104.png" -OutFile "Pictures/Transparent Pics/Achievement104.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement105.png" -OutFile "Pictures/Transparent Pics/Achievement105.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement106.png" -OutFile "Pictures/Transparent Pics/Achievement106.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement107.png" -OutFile "Pictures/Transparent Pics/Achievement107.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement108.png" -OutFile "Pictures/Transparent Pics/Achievement108.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement109.png" -OutFile "Pictures/Transparent Pics/Achievement109.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement110.png" -OutFile "Pictures/Transparent Pics/Achievement110.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement111.png" -OutFile "Pictures/Transparent Pics/Achievement111.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement112.png" -OutFile "Pictures/Transparent Pics/Achievement112.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement113.png" -OutFile "Pictures/Transparent Pics/Achievement113.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement114.png" -OutFile "Pictures/Transparent Pics/Achievement114.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement115.png" -OutFile "Pictures/Transparent Pics/Achievement115.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement116.png" -OutFile "Pictures/Transparent Pics/Achievement116.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement117.png" -OutFile "Pictures/Transparent Pics/Achievement117.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement118.png" -OutFile "Pictures/Transparent Pics/Achievement118.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement119.png" -OutFile "Pictures/Transparent Pics/Achievement119.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement120.png" -OutFile "Pictures/Transparent Pics/Achievement120.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement121.png" -OutFile "Pictures/Transparent Pics/Achievement121.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement122.png" -OutFile "Pictures/Transparent Pics/Achievement122.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement123.png" -OutFile "Pictures/Transparent Pics/Achievement123.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement124.png" -OutFile "Pictures/Transparent Pics/Achievement124.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement125.png" -OutFile "Pictures/Transparent Pics/Achievement125.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement126.png" -OutFile "Pictures/Transparent Pics/Achievement126.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement127.png" -OutFile "Pictures/Transparent Pics/Achievement127.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement128.png" -OutFile "Pictures/Transparent Pics/Achievement128.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement129.png" -OutFile "Pictures/Transparent Pics/Achievement129.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement130.png" -OutFile "Pictures/Transparent Pics/Achievement130.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement131.png" -OutFile "Pictures/Transparent Pics/Achievement131.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement132.png" -OutFile "Pictures/Transparent Pics/Achievement132.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement133.png" -OutFile "Pictures/Transparent Pics/Achievement133.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement134.png" -OutFile "Pictures/Transparent Pics/Achievement134.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement135.png" -OutFile "Pictures/Transparent Pics/Achievement135.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement136.png" -OutFile "Pictures/Transparent Pics/Achievement136.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement137.png" -OutFile "Pictures/Transparent Pics/Achievement137.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement138.png" -OutFile "Pictures/Transparent Pics/Achievement138.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement139.png" -OutFile "Pictures/Transparent Pics/Achievement139.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement140.png" -OutFile "Pictures/Transparent Pics/Achievement140.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement141.png" -OutFile "Pictures/Transparent Pics/Achievement141.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement142.png" -OutFile "Pictures/Transparent Pics/Achievement142.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement143.png" -OutFile "Pictures/Transparent Pics/Achievement143.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement144.png" -OutFile "Pictures/Transparent Pics/Achievement144.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement145.png" -OutFile "Pictures/Transparent Pics/Achievement145.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement146.png" -OutFile "Pictures/Transparent Pics/Achievement146.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Achievement147.png" -OutFile "Pictures/Transparent Pics/Achievement147.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/CrystalOne.png" -OutFile "Pictures/Transparent Pics/CrystalOne.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/CrystalTen.png" -OutFile "Pictures/Transparent Pics/CrystalTen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/CrystalHundred.png" -OutFile "Pictures/Transparent Pics/CrystalHundred.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/DiamondTier1.png" -OutFile "Pictures/DiamondTier1.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/DiamondTier2.png" -OutFile "Pictures/DiamondTier2.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/DiamondTier3.png" -OutFile "Pictures/DiamondTier3.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/DiamondTier4.png" -OutFile "Pictures/DiamondTier4.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/DiamondTier5.png" -OutFile "Pictures/DiamondTier5.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/CrystalUpgrade1.png" -OutFile "Pictures/Transparent Pics/CrystalUpgrade1.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/CrystalUpgrade2.png" -OutFile "Pictures/Transparent Pics/CrystalUpgrade2.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/CrystalUpgrade3.png" -OutFile "Pictures/Transparent Pics/CrystalUpgrade3.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/CrystalUpgrade4.png" -OutFile "Pictures/Transparent Pics/CrystalUpgrade4.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/CrystalUpgrade5.png" -OutFile "Pictures/Transparent Pics/CrystalUpgrade5.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/OfferingOne.png" -OutFile "Pictures/Transparent Pics/OfferingOne.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/OfferingTen.png" -OutFile "Pictures/Transparent Pics/OfferingTen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/OfferingHundred.png" -OutFile "Pictures/Transparent Pics/OfferingHundred.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/SpeedRune.png" -OutFile "Pictures/Transparent Pics/SpeedRune.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/DuplicationRune.png" -OutFile "Pictures/Transparent Pics/DuplicationRune.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/PrismRune.png" -OutFile "Pictures/Transparent Pics/PrismRune.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/ThriftRune.png" -OutFile "Pictures/Transparent Pics/ThriftRune.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/MythosOne.png" -OutFile "Pictures/Transparent Pics/MythosOne.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/MythosTen.png" -OutFile "Pictures/Transparent Pics/MythosTen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/MythosHundred.png" -OutFile "Pictures/Transparent Pics/MythosHundred.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/MythosTier1.png" -OutFile "Pictures/MythosTier1.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/MythosTier2.png" -OutFile "Pictures/MythosTier2.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/MythosTier3.png" -OutFile "Pictures/MythosTier3.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/MythosTier4.png" -OutFile "Pictures/MythosTier4.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/MythosTier5.png" -OutFile "Pictures/MythosTier5.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/ParticleOne.png" -OutFile "Pictures/Transparent Pics/ParticleOne.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/ParticleTen.png" -OutFile "Pictures/Transparent Pics/ParticleTen.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/ParticleHundred.png" -OutFile "Pictures/Transparent Pics/ParticleHundred.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/ParticlesTier1.png" -OutFile "Pictures/ParticlesTier1.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/ParticlesTier2.png" -OutFile "Pictures/ParticlesTier2.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/ParticlesTier3.png" -OutFile "Pictures/ParticlesTier3.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/ParticlesTier4.png" -OutFile "Pictures/ParticlesTier4.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/ParticlesTier5.png" -OutFile "Pictures/ParticlesTier5.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research1.png" -OutFile "Pictures/Transparent Pics/Research1.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research2.png" -OutFile "Pictures/Transparent Pics/Research2.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research3.png" -OutFile "Pictures/Transparent Pics/Research3.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research4.png" -OutFile "Pictures/Transparent Pics/Research4.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research5.png" -OutFile "Pictures/Transparent Pics/Research5.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research26.png" -OutFile "Pictures/Transparent Pics/Research26.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research27.png" -OutFile "Pictures/Transparent Pics/Research27.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research28.png" -OutFile "Pictures/Transparent Pics/Research28.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research29.png" -OutFile "Pictures/Transparent Pics/Research29.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research30.png" -OutFile "Pictures/Transparent Pics/Research30.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research51.png" -OutFile "Pictures/Transparent Pics/Research51.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research52.png" -OutFile "Pictures/Transparent Pics/Research52.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research53.png" -OutFile "Pictures/Transparent Pics/Research53.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research54.png" -OutFile "Pictures/Transparent Pics/Research54.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research55.png" -OutFile "Pictures/Transparent Pics/Research55.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research6.png" -OutFile "Pictures/Transparent Pics/Research6.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research7.png" -OutFile "Pictures/Transparent Pics/Research7.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research8.png" -OutFile "Pictures/Transparent Pics/Research8.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research9.png" -OutFile "Pictures/Transparent Pics/Research9.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research10.png" -OutFile "Pictures/Transparent Pics/Research10.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research31.png" -OutFile "Pictures/Transparent Pics/Research31.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research32.png" -OutFile "Pictures/Transparent Pics/Research32.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research33.png" -OutFile "Pictures/Transparent Pics/Research33.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research34.png" -OutFile "Pictures/Transparent Pics/Research34.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research35.png" -OutFile "Pictures/Transparent Pics/Research35.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research56.png" -OutFile "Pictures/Transparent Pics/Research56.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research57.png" -OutFile "Pictures/Transparent Pics/Research57.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research58.png" -OutFile "Pictures/Transparent Pics/Research58.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research59.png" -OutFile "Pictures/Transparent Pics/Research59.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research60.png" -OutFile "Pictures/Transparent Pics/Research60.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research11.png" -OutFile "Pictures/Transparent Pics/Research11.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research12.png" -OutFile "Pictures/Transparent Pics/Research12.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research13.png" -OutFile "Pictures/Transparent Pics/Research13.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research14.png" -OutFile "Pictures/Transparent Pics/Research14.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research15.png" -OutFile "Pictures/Transparent Pics/Research15.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research36.png" -OutFile "Pictures/Transparent Pics/Research36.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research37.png" -OutFile "Pictures/Transparent Pics/Research37.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research38.png" -OutFile "Pictures/Transparent Pics/Research38.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research39.png" -OutFile "Pictures/Transparent Pics/Research39.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research40.png" -OutFile "Pictures/Transparent Pics/Research40.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research61.png" -OutFile "Pictures/Transparent Pics/Research61.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research62.png" -OutFile "Pictures/Transparent Pics/Research62.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research63.png" -OutFile "Pictures/Transparent Pics/Research63.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research64.png" -OutFile "Pictures/Transparent Pics/Research64.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research65.png" -OutFile "Pictures/Transparent Pics/Research65.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research16.png" -OutFile "Pictures/Transparent Pics/Research16.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research17.png" -OutFile "Pictures/Transparent Pics/Research17.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research18.png" -OutFile "Pictures/Transparent Pics/Research18.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research19.png" -OutFile "Pictures/Transparent Pics/Research19.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research20.png" -OutFile "Pictures/Transparent Pics/Research20.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research41.png" -OutFile "Pictures/Transparent Pics/Research41.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research42.png" -OutFile "Pictures/Transparent Pics/Research42.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research43.png" -OutFile "Pictures/Transparent Pics/Research43.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research44.png" -OutFile "Pictures/Transparent Pics/Research44.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research45.png" -OutFile "Pictures/Transparent Pics/Research45.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research66.png" -OutFile "Pictures/Transparent Pics/Research66.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research67.png" -OutFile "Pictures/Transparent Pics/Research67.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research68.png" -OutFile "Pictures/Transparent Pics/Research68.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research69.png" -OutFile "Pictures/Transparent Pics/Research69.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research70.png" -OutFile "Pictures/Transparent Pics/Research70.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research21.png" -OutFile "Pictures/Transparent Pics/Research21.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research22.png" -OutFile "Pictures/Transparent Pics/Research22.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research23.png" -OutFile "Pictures/Transparent Pics/Research23.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research24.png" -OutFile "Pictures/Transparent Pics/Research24.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research25.png" -OutFile "Pictures/Transparent Pics/Research25.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research46.png" -OutFile "Pictures/Transparent Pics/Research46.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research47.png" -OutFile "Pictures/Transparent Pics/Research47.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research48.png" -OutFile "Pictures/Transparent Pics/Research48.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research49.png" -OutFile "Pictures/Transparent Pics/Research49.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research50.png" -OutFile "Pictures/Transparent Pics/Research50.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research71.png" -OutFile "Pictures/Transparent Pics/Research71.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research72.png" -OutFile "Pictures/Transparent Pics/Research72.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research73.png" -OutFile "Pictures/Transparent Pics/Research73.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research74.png" -OutFile "Pictures/Transparent Pics/Research74.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transparent Pics/Research75.png" -OutFile "Pictures/Transparent Pics/Research75.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Prestige.png" -OutFile "Pictures/Prestige.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Transcend.png" -OutFile "Pictures/Transcend.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/Reincarnate.png" -OutFile "Pictures/Reincarnate.png"
Invoke-WebRequest -Uri "http://game320578.konggames.com/gamez/0032/0578/live/Pictures/discordserveravatar.png" -OutFile "Pictures/discordserveravatar.png"
